title: Take the minimum
author: LiuCong
email: 1658246485@qq.com
description: > # this means to ignore newlines until "baseurl:"
  In practical engineering applications, many times we need to find the minimum value, such as the minimum cost, or the shortest path  

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
